name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get -qq update
          git clone https://github.com/fletcher/MultiMarkdown-6.git /tmp/mmd
          (cd /tmp/mmd && make release && cd build && make && sudo make install)
          git clone https://github.com/avioli/jenny.git /tmp/jenny
          (cd /tmp/jenny; sudo make install)
          mkdir .dist

      - name: Build
        run: jenny
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
